name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Adjust this to the root of your application
          api_location: ""  # Leave empty if you don't have an API
          output_location: "build"  # Adjust this to your build output folder
